# Generated by Django 4.2 on 2024-02-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_status', models.CharField(default='Submission', max_length=15)),
            ],
            options={
                'db_table': 'insurance_application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('serial_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'insurance_vehicle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsuranceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('insurance_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.insuranceapplication')),
            ],
            options={
                'db_table': 'insurance_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.vehicle')),
            ],
            options={
                'db_table': 'insurance_driver',
                'managed': True,
            },
        ),
    ]
