# Generated by Django 4.2 on 2024-02-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancestatus',
            name='status',
            field=models.CharField(choices=[('SUBMISSION', 'Submission'), ('REVIEW', 'Review'), ('APPROVAL', 'Approval'), ('REJECTION', 'Rejection')], max_length=15),
        ),
    ]
