# Generated by Django 4.2 on 2024-02-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurancestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.EmailField(max_length=100),
        ),
    ]
