# Generated by Django 4.2 on 2024-02-02 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0004_alter_driver_address_alter_driver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceapplication',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insurance.driver'),
        ),
        migrations.AddField(
            model_name='insuranceapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
