# Generated by Django 4.2 on 2024-02-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insuranceapplication_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancestatus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
