# Generated by Django 4.2 on 2024-02-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_insuranceapplication_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapplication',
            name='active_status',
            field=models.CharField(choices=[('SUBMISSION', 'Submission'), ('REVIEW', 'Review'), ('APPROVAL', 'Approval'), ('REJECTION', 'Rejection')], default='Submission', max_length=15),
        ),
    ]
