# Generated by Django 4.2 on 2024-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_alter_insuranceapplication_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceapplication',
            name='active_status',
            field=models.CharField(choices=[('Submission', 'Submission'), ('Review', 'Review'), ('Approval', 'Approval'), ('Rejection', 'Rejection')], default='Submission', max_length=15),
        ),
        migrations.AlterField(
            model_name='insurancestatus',
            name='status',
            field=models.CharField(choices=[('Submission', 'Submission'), ('Review', 'Review'), ('Approval', 'Approval'), ('Rejection', 'Rejection')], max_length=15),
        ),
    ]
